### ISSUE TITLE
Update dev setup and dependencies for 4.0-beta

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1213]
I'd like to review our dev setup for 4.0-beta. Some of the things already have their own issues but it might be easier to do all of the updates in a fewer number of PRs (probably still multiple).

- [x] Update VP project (PHP). Done mostly in Dockerized dev setup, https://github.com/versionpress/versionpress/pull/1227.
- [x] Update frontend project (TypeScript / React): PR https://github.com/versionpress/versionpress/pull/1214
- [x] ~~npm -> Yarn~~ won't happen, see https://github.com/versionpress/versionpress/issues/1142#issuecomment-309294152
    - [x] Revert parts of https://github.com/versionpress/versionpress/pull/1214 in a separate PR; frontend already switched to Yarn. _done in Dockerized dev setup #1227_
- [x] Update .idea template files #1144
    - [x] This has also happened in Dockerized dev setup #1227
- [x] PhpStorm inspections _done in Dockerized dev setup #1227_
- ~~Adopt PHPStan~~ see separate issue #1210
- ~~Review and update Dev-Setup.md~~ -> part of Dockerized dev setup #1227
- ~~Gulp -> npm scripts?~~ Won't happen at this point.
