### ISSUE TITLE
Docs issues from the retired `docs` repo

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1219]
The `docs` repo is being retired (https://github.com/versionpress/versionpress/pull/1218), here are the currently open docs issues that should be resolved here:

- [ ] Document post tracking flow https://github.com/versionpress/docs/issues/6
- [ ] Document configurable entity ignoring (#511) https://github.com/versionpress/docs/issues/12
- [ ] Transfer release notes to the main repo https://github.com/versionpress/docs/issues/26
- [ ] Update links to HTTPS https://github.com/versionpress/docs/issues/31
- [ ] Mention 2.x configuration mechanism on the configuration page https://github.com/versionpress/docs/issues/44
- [ ] Warn about stricter system requirements for multi-environment workflows https://github.com/versionpress/docs/issues/56
- [ ] Document plugins / themes installed via Composer (#1037) https://github.com/versionpress/docs/issues/59
