### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1259]
With Dockerized tests (#1227) we're ready to set up Travis CI for this repo. Here's their docs page: [Using Docker in Builds - Travis CI](https://docs.travis-ci.com/user/docker/).

---

🏁 

- [x] Initial implementation was #1381. We reverted it in #1394 as the tests were failing at that point.
- [x] Tests were improved in #1389 and are passing since #1400.
- [ ] With that, there's a new PR adding Travis CI build, #1415.

**Comment by borekb** [comment]
Resolved by #1381. 🎉

**Comment by borekb** [comment]
I've reverted #1381 with #1394 for reason given in that PR:

> I'm going to revert the Travis CI setup temporarily as all the builds fail right now (#1383) and it's not very useful to have CI running at this point. Quite to the contrary, e.g., Markdown changes that are fine are flagged as failed even though they're correct.

I'm also going to reopen this issue and based on the experience that #1381 gave us, update the issue description.

**Comment by borekb** [comment]
Travis also [added Windows support](https://blog.travis-ci.com/2018-10-11-windows-early-release) recently, that would be useful to set up as well.

**Comment by borekb** [comment]
Moving the following notes from the issue description here as we won't implement it that properly for now:

---

**UPDATE 03/2019**: Based on our experience with #1381, it's now clearer what we want from a CI setup:

- The builds should respect that this repo is a monorepo and only check what needs to be checked. For example, with #1381 setup, if I updated a Markdown file in the `docs` folder, full tests were still started (they used to take over an hour at that point), Docker images were built (incl. pulling all the base layers), etc. which is both wasteful and also makes it harder to debug the actual issue as the reported problems might come from different parts of the repo.

    Examples of separated builds:
    
    - Changes in `docs` trigger Markdown linting & Netlify preview deployment.
    - Changes in `plugins/versionpress` run full tests.
    - Changes in `frontend` run `tsc`, TSLint and frontend tests.
    - Changes in `dev-env/wordpress-[cli-]image` trigger Docker build.

    Multiple paths can be affected in a single PR which should trigger all related CI tasks, for example, if a UI is updated and there's a new screenshot in the docs, points 1 and 3 from above should run.

- It should be documented how to test the Travis setup without affecting current PR builds. [Local workflow](https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally) would be ideal, IMO, but anything that can be done separately from the main repo (e.g., in a private fork) is fine.

- Test reporting is not very nice at the moment – notice how the dots (progress) interleave with testdox output:<br><br>![image](https://user-images.githubusercontent.com/101152/54076260-ed522280-42a9-11e9-978b-957eb064d79b.png)

**Comment by borekb** [comment]
Travis is now running full tests for each PR & merges to `master` 🎉 . [This is the first successful build of master](https://travis-ci.org/versionpress/versionpress/builds/516254002).

The only unpleasant thing is the lack of Docker caching for which I've created a separate issue #1419. We can close this now.

Thanks @candrews for your help!
