### ISSUE TITLE
4.0-beta release checklist

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1263]
- [x] Check that all closed issues are assigned to the correct [4.0 milestone](https://github.com/versionpress/versionpress/milestones/4.0) and the [4.0-beta project](https://github.com/versionpress/versionpress/projects/2). Here's a [useful search filter](https://github.com/versionpress/versionpress/issues?utf8=%E2%9C%93&q=closed%3A2016-10-11..2017-07-10%20no%3Aproject%20-label%3Asupport) (ignore issues from older milestones).
- [x] Take the opportunity to update README, do some final cleanup https://github.com/versionpress/versionpress/pull/1283
- [x] Run automated tests
- [x] Build a ZIP file
- [x] Smoke tests on WP 4.8 + Twenty Seventeen:
    - [x] Installation, activation
    - [x] DB tracking (adding posts, updating options)
    - [x] File tracking (installing plugins & themes)
    - [x] Search
    - [x] Undo
    - [x] Rollback
    - [x] Cloning & merging
- [x] Write release notes https://github.com/versionpress/versionpress/pull/1270
- [x] Tag a release, copy release notes there https://github.com/versionpress/versionpress/releases/tag/4.0-beta
- [x] Write a release blog post https://github.com/versionpress/blogposts/pull/30
- [x] PUSH THE RED BUTTON 🔴 

Announcements:

- [x] Blog post https://blog.versionpress.net/2017/07/versionpress-4-0-beta/
- [x] Newsletter http://mailchi.mp/versionpress/versionpress-40-beta-is-ready
- [x] Tweet https://twitter.com/versionpress/status/884088459169869828
- [x] FB post https://www.facebook.com/VersionPress/posts/1971623079530513
- [x] Gitter https://gitter.im/versionpress/versionpress?at=5962577bbf7e6af22cbe6b88
- [x] Social where appropriate ([ManageWP](https://managewp.org/articles/15615/versionpress-4-0-beta), AWP, Reddit, ...)

**Comment by borekb** [comment]
🎉 

4.0-beta is out
