### ISSUE TITLE
Improve Dockerized testing infrastructure

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1389]
Full tests (`npm run tests:full`) currently take over an hour to run on a relatively powerful machine (Core i7 MacBook Pro) and there are some other issues related to tests as we reviewed them with @JanVoracek today.

**UPDATE**: In the end, this issue is a relatively major update of the dockerized dev / testing environment last updated in #1329.

### Highlights

- Full tests now run _much_ faster thanks to volumes instead of host-mounted folders. On my machine, the time dropped from **1 hour 15 minutes** to just **11 minutes**. #1396
- Permissions between containers (Debian vs. Alpine) have been fixed. #1397
- New `run-tests.ts` script that orchestrates how tests run. For example, it decides when to start a WordPress stack (if at all), cleans up after itself, etc. #1401
- The main testing scripts is now just `npm run tests` (the `:full` suffix has been dropped).
    - Also, all the `tests:custom` scripts have been dropped as `run-tests.ts` now accepts parameters, for example:<br>`npm run tests -- --testsuite Unit --filter CursorTest`
- Docker images are now fixed using their digests. No more surprises if upstream images change. #1398
- Some effort has been put into testing and documenting how test work on Docker Toolbox. #1403

During the work, I've also encountered several other things that are noted in the "Deferred items" section below.

### TODO list

- [x] Split testing documentation from Dev Setup, it's quite long on its own. #1392
    - [x] ... and smaller related content changes. #1393
- [x] Split docker-compose services into two files, `docker-compose.yml` and `docker-compose.tests.yml`. #1395
- [x] ⭐ Permissions: Run CLI image as UID 33 (Debian's "www-data") #1397
- [x] ⭐ Volumes: use named volumes (i.e., don't map to host OS) & have some way to inspect the data later. #1396
- [x] Use Docker image digests instead of tags. #1398
    - They are uglier, e.g., `busybox:latest` becomes `busybox@sha256:38a203e1986cf79639cfb9b2e1d6e773de84002feea2d4eb006b52004ee8502d`, but it's the only way to make runs predictable (docker-compose lacks a concept of a lock file).
    - This has already been considered in https://github.com/versionpress/versionpress/pull/1329 but we eventually didn't go for it.
    - `docker-compose config --resolve-image-digests` can help with that.
    - Awesome post about the problem and solutions: [Overcoming Docker’s mutable image tags](https://renovatebot.com/blog/docker-mutable-tags)
        - (BTW, it's by [Renovate](https://renovatebot.com), a tool that we should consider in the future anyway to keep dependencies up to date.)
- [x] Stop containers after the tests finish running. #1399 (`package.json` impl), then #1401 (`run-tests.ts` impl)
- [x] ⭐ Introduce `run-tests.ts` and make test runs more reliable. #1400 (PR #1401)
- [x] Verify how things work in Docker Toolbox. #1403
- [x] Possibly remove "test:custom" npm scripts, just document how to do it. _Done as part of #1401._
- [x] Explore using Samba to speed up files inspection, see https://github.com/versionpress/versionpress/issues/1389#issuecomment-471550657. _Explored but not successfully, see #1411._
- [x] Document how to stop tests on Mac – Ctrl+C doesn't work, I have to open another terminal, type `docker ps`, copy the container ID and do `docker stop <id>`. _Resolved as part of #1401 – Ctrl+C now kills the Node.js script._
    - https://github.com/docker/compose/issues/3317
    - https://github.com/docker/compose/issues/3347
    - Might be an issue with wordpress:cli entrypoint and how it handles signals.
- [x] ⭐ Make `npm run tests` pass. #1400

### Deferred items

These should be done separately in future PRs.

- Rename images to something like `versionpress/wordpress` and `versionpress/cli`, i.e., make "CLI" part of the image name so that it's clear when digests are used.
- Only enable Xdebug for `...:debug` scripts.
    - Right now, it's always enabled and just not configured with the right idekey in non-debug scripts which makes things slower. [Here](https://github.com/versionpress/versionpress/blob/ecbcd618ab4c21069c2fc3ff9e18ac3f34773b0e/dev-env/wordpress-image/Dockerfile#L20-L25) and [here](https://github.com/versionpress/versionpress/blob/ecbcd618ab4c21069c2fc3ff9e18ac3f34773b0e/dev-env/wordpress-cli-image/Dockerfile#L12-L19). 
    - Update Xdebug to 2.7.0. (Let's still stay on PHP 7.2 for tests for now.)
- Make PHP 7.2 the minimum required version? (We don't have an issue for it yet, will create it.)
- The WP-CLI installation into the WP image looks [a bit weird](https://github.com/versionpress/versionpress/blob/ecbcd618ab4c21069c2fc3ff9e18ac3f34773b0e/dev-env/wordpress-image/Dockerfile#L10-L16), review it.
- Try updating PHPUnit (I remember it wasn't so easy due to supported PHP versions or something but it's worth looking again).
- Don't base our CLI image on [wordpress:cli](https://github.com/docker-library/wordpress/blob/aecdd7dcc8e9dd923d3096d353fa70d63de26a1b/php7.2/cli/Dockerfile), it does a lot more than we need.
- Explore re-running failed tests: https://github.com/sebastianbergmann/phpunit/issues/46
- Close #1284 (Fix remaining tests under Docker, post-beta) and port those to a new issue
- Review backlog from the "Noted for future work" section in #1329
- Another big one is #1258 (WP-CLI / Selenium worker switching). That issue is a bit old but overall, we should still be able to run all tests with both workers, or pick a worker with a flag like `npm run tests --worker=selenium`. Things like a worker or a specific test site to use shouldn't be hardcoded in `test-config.yml`.
    - Related: [How to parametrize PHPUnit tests](https://stackoverflow.com/questions/8491437/pass-variable-to-phpunit).

**Comment by borekb** [comment]
Good progress this weekend:

![image](https://user-images.githubusercontent.com/101152/54093362-7eeb8e00-4397-11e9-8463-3344e57cb827.png)

@pavelevap, could you please try how tests currently work on Windows? For me, `npm run tests:full` (after `npm run tests:cleanup`!) take about **10 minutes to run** and produce only **1 failure** in `CloneMergeTest::cloneLooksExactlySameAsOriginal` ("Tests: 738, Assertions: 950, Failures: 1, Skipped: 16").

If we could fix that issue, that would be a big win.

**Comment by borekb** [comment]
Named volumes implemented in #1396 made things much faster but also harder to inspect files locally. The [current solution](https://github.com/versionpress/versionpress/blob/b9e6cc356d4377819e5e65512da5af71562a7ecf/docker-compose-tests.yml#L63-L70) depends on copying files from a named volumed to a folder that will be bind-mount to host but this is quite slow (several minutes of heavy I/O on my Mac).

[This SO answer](https://stackoverflow.com/a/55098178/21728) suggests using Samba, we could explore that as an alternative.

**Comment by borekb** [comment]
The key items are done and the tests now fully pass 🎉.

I've updated the original description to contain all the relevant details.
