### ISSUE TITLE
Testing infrastructure – backlog

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1412]
With #1389, the most pressing issues with testing have been fixes. This is a backlog of other items that we should do in the near future:

- [ ] Only enable Xdebug for `...:debug` scripts. Right now, it's always enabled and just not configured with the right idekey in non-debug scripts which makes things slower. [Here](https://github.com/versionpress/versionpress/blob/ecbcd618ab4c21069c2fc3ff9e18ac3f34773b0e/dev-env/wordpress-image/Dockerfile#L20-L25) and [here](https://github.com/versionpress/versionpress/blob/ecbcd618ab4c21069c2fc3ff9e18ac3f34773b0e/dev-env/wordpress-cli-image/Dockerfile#L12-L19), also mentioned here: https://github.com/versionpress/versionpress/pull/1227#discussion_r117698433.
- [ ] Update Xdebug to 2.7.0.
- [ ] Rename images to something like `versionpress/wordpress` and `versionpress/cli`, i.e., make "CLI" part of the image name so that it's clear when digests are used.
- [ ] Review [WP-CLI installation into the WP image](https://github.com/versionpress/versionpress/blob/ecbcd618ab4c21069c2fc3ff9e18ac3f34773b0e/dev-env/wordpress-image/Dockerfile#L10-L16), it looks a bit weird.
- [ ] Update PHPUnit. Depends on minimum required version bump, see #1408.
- [ ] Don't base our CLI image on [wordpress:cli](https://github.com/docker-library/wordpress/blob/aecdd7dcc8e9dd923d3096d353fa70d63de26a1b/php7.2/cli/Dockerfile), it does a lot more than we need.
- [ ] Explore re-running only failed tests: https://github.com/sebastianbergmann/phpunit/issues/46
- [ ] Close #1284 (Fix remaining tests under Docker, post-beta) and port those to a new issue
- [ ] Review backlog from the "Noted for future work" section in #1329
- [ ] Another big one is #1258 (WP-CLI / Selenium worker switching). That issue is a bit old but overall, we should still be able to run all tests with both workers, or pick a worker with a flag like `npm run tests --worker=selenium`. Things like a worker or a specific test site to use shouldn't be hardcoded in `test-config.yml`.
    - Related: [How to parametrize PHPUnit tests](https://stackoverflow.com/questions/8491437/pass-variable-to-phpunit).
